<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/SBProject/dbAdapter" name="dbAdapter-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbAdapter.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/SBProject/dbAdapter"/>
    <wsdl:binding name="dbAdapter_ptt-binding" type="dbad:dbAdapter_ptt" xmlns:dbad="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/SBProject/dbAdapter">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbAdapterSelect">
            <soap:operation soapAction="dbAdapterSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>